### ISSUE TITLE
[BUG] Proxy disable ipv6

### ISSUE THREAD

**Issue by Soneji** [adw0rd/instagrapi#366] opened 2021-09-09 19:29 UTC
**Describe the bug**
Proxy not working with IPv6 networking. I want a way to force instagrapi to use IPv4 networking. 

**To Reproduce**
```py
cl.set_proxy(os.environ['PROXY'])
cl.login(username=username, password=password)
```
This is the proxy I am using 
https://hub.docker.com/r/serjs/go-socks5-proxy/

**Traceback**
<details>

```python
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/socks.py", line 809, in connect
    negotiate(self, dest_addr, dest_port)
  File "/app/env/lib/python3.8/site-packages/socks.py", line 443, in _negotiate_SOCKS5
    self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
  File "/app/env/lib/python3.8/site-packages/socks.py", line 533, in _SOCKS5_request
    raise SOCKS5Error("{:#04x}: {}".format(status, error))
socks.SOCKS5Error: 0x04: Host unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/urllib3/contrib/socks.py", line 96, in _new_conn
    conn = socks.create_connection(
  File "/app/env/lib/python3.8/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/app/env/lib/python3.8/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/app/env/lib/python3.8/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/app/env/lib/python3.8/site-packages/socks.py", line 814, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x04: Host unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/app/env/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/app/env/lib/python3.8/site-packages/urllib3/contrib/socks.py", line 127, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106bd3400>: Failed to establish a new connection: 0x04: Host unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/app/env/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /rupload_igvideo/1631214926017_0_3282549194 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106bd3400>: Failed to establish a new connection: 0x04: Host unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 23, in <module>
    main()
  File "./test.py", line 20, in main
    post_to_instagram(file, caption, username, password)
  File "/app/src/post.py", line 23, in post_to_instagram
    cl.clip_upload(path=file, caption=caption)
  File "/app/env/lib/python3.8/site-packages/instagrapi/mixins/clip.py", line 132, in clip_upload
    response = self.private.get(
  File "/app/env/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/app/env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/app/env/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /rupload_igvideo/1631214926017_0_3282549194 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106bd3400>: Failed to establish a new connection: 0x04: Host unreachable'))
```

</details>

**Expected behavior**
I would like for an option where I can set the networking in the app to only use IPv4

**Desktop (please complete the following information):**
 - OS: macOS 11.5
 - Python version: 3.8.2
<details>
<summary>Other versions</summary>

```
beautifulsoup4==4.10.0
bs4==0.0.1
certifi==2021.5.30
charset-normalizer==2.0.4
idna==3.2
instagrapi==1.9.19
Pillow==8.3.2
pycryptodomex==3.9.9
pydantic==1.8.2
PySocks==1.7.1
python-dotenv==0.19.0
requests==2.26.0
soupsieve==2.2.1
typing-extensions==3.10.0.2
urllib3==1.26.6
```

</details>

**Comment by adw0rd** [comment] 2021-09-09 21:01
@Soneji show what's in `os.environ['PROXY']`

**Comment by Soneji** [comment] 2021-09-09 21:15
```sh
PROXY=socks5://user:pass@website.com:XXXXX
```
I know it works when I curl like this

```sh
curl -4 -v -x socks5://user:pass@website.com:XXXXX http://www.google.com/
```

Without the 4 option it shows this error
```sh
*   Trying X.X.X.X... // <- this is my proxy IP
* TCP_NODELAY set
* SOCKS5 communication to www.google.com:80
* SOCKS5 connect to IPv6 2a00:1450:4009:818::2004 (locally resolved)
* Can't complete SOCKS5 connection to 0.0.0.0:0. (4)
* Closing connection 0
curl: (7) Can't complete SOCKS5 connection to 0.0.0.0:0. (4)
```

**Comment by adw0rd** [comment] 2021-09-10 15:56
@Soneji cannot reproduce:

![image](https://user-images.githubusercontent.com/546889/132879433-69763673-0612-498d-8e6e-f4b3b867962c.png)

**Comment by Soneji** [comment] 2021-09-10 20:11
I don't think you'll be able to reproduce it, you have to be on an IPv6 network which my ISP uses

**Comment by adw0rd** [comment] 2021-09-10 21:46
@Soneji then I will assign this issue to you

**Comment by Soneji** [comment] 2021-09-13 22:08
I don't think I'll be able to fix this, I am using `instagrapi-rest` now. 

If you want to unassign me and close it feel free to. 

If anybody else runs into this I imagine a solutioin could be one of:
- using `instagrapi-rest` instead of setting up a proxy server
- setting up the proxy to work with IPv6
- disabling IPv6 on your system
- Actually fixing the issue in the python code which seems kinda hacky from what I've read (https://stackoverflow.com/questions/33046733/force-requests-to-use-ipv4-ipv6)

**Closed** 2021-09-13 22:56 UTC
Labels: bug
